### ISSUE TITLE
Add strategy design pattern

### ISSUE THREAD

**Issue by egeldenhuys** [RagingGrim/DesignPatterns#1]

**Comment by CDuPlooy** [comment]
Uploaded in commit (49549f0)

Does it look fine to you?

**Comment by egeldenhuys** [comment]
Scanning your function names it seems like a practical example. Good work with implementing it using a strategy DP. Will review it more thoroughly tomorrow. I think it is better than what I was working on.

Would it be acceptable to have multiple examples per DP in the repo? That way people might be able to more easily learn the pattern connected to the DP.

If people fork, implement the pattern on their repo, and then send a pull request to your repo, we have a central place to give and receive feedback. We do not necessarily have to merge into this repo.

I will fork a fresh one and send some Pull Requests and we can see how it works.

**Comment by CDuPlooy** [comment]
The way I see it , the more people contributing the better. 

I have to HAND it to you , your example was good too :hand:
