### ISSUE TITLE
Move examples of same pattern to single folder

### ISSUE THREAD

**Issue by egeldenhuys** [RagingGrim/DesignPatterns#3]
Currently we have single .cpp files in a directory, which is rather cumbersome to navigate.

I suggest we place the examples in the pattern root directory and name them something like "example-1.cpp" or "memento-ex1.cpp"

**Comment by CDuPlooy** [comment]
I'm not entirely sure if I understood correctly , I thought it would be nice to have folders for every example of a particular pattern. The file names could then be elementary.

Commit cf0f7ac has seperate directories for each example by every contributer ( active contributers anyway :p )

**Comment by egeldenhuys** [comment]
I think your solution is better than my proposition as it allows for more complex examples without conflicting files names.
